// packages/message-archive/web/src/lib/components/media-lightbox.svelte
<script lang="ts">
  import Dialog from "$lib/components/ui/dialog.svelte";
  import type { LightboxItem } from "$lib/types";

  let { item, onClose }: { item: LightboxItem | null; onClose: () => void } = $props();
</script>

<Dialog open={item !== null} onOpenChange={(open) => !open && onClose()} contentClass="max-w-3xl" hideClose={false}>
  {#if item}
    <div class="max-h-[75vh] w-full overflow-auto rounded-md bg-muted/20">
      <img src={item.src} alt={item.alt} class="w-full object-contain" loading="lazy" decoding="async" />
    </div>
  {/if}
</Dialog>

// packages/message-archive/web/src/components/media-lightbox.tsx
import {
  Dialog,
  DialogContent,
  DialogTitle
} from "@/components/ui/dialog";
import type { LightboxItem } from "@/lib/types";

export function MediaLightbox({
  item,
  onClose
}: {
  readonly item: LightboxItem | null;
  readonly onClose: () => void;
}) {
  return (
    <Dialog open={item !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-3xl">
        <DialogTitle className="sr-only">图片预览</DialogTitle>
        {item ? <img src={item.src} alt={item.alt} className="max-h-[75vh] w-full rounded-md object-contain" /> : null}
      </DialogContent>
    </Dialog>
  );
}
