// packages/message-archive/web/src/lib/components/media-gallery.svelte
<script lang="ts">
  import MediaThumb from "$lib/components/media-thumb.svelte";
  import { api } from "$lib/api";
  import { cn } from "$lib/utils";
  import type { LightboxItem, MediaItem, SearchRow } from "$lib/types";

  let {
    row,
    onOpen,
    class: className = ""
  }: { row: SearchRow; onOpen: (item: LightboxItem) => void; class?: string } = $props();

  function initialMedia(): MediaItem[] {
    return row.media_items.filter((media) => media && media.media_url);
  }
  let items: readonly MediaItem[] = $state(initialMedia());
  let expanded = false;

  function expandAlbum(): void {
    if (expanded || initialMedia().length > 1) return;
    expanded = true;
    api
      .album(row.id)
      .then((album) => {
        if (album.length > initialMedia().length) items = album;
      })
      .catch(() => undefined);
  }
</script>

{#if items.length > 0}
  <div class={cn("flex flex-wrap gap-2", className)}>
    {#each items as media, index (`${media.media_url}${media.message_id ?? ""}`)}
      <MediaThumb {media} {index} {onOpen} onExpand={expandAlbum} />
    {/each}
  </div>
{/if}

// packages/message-archive/web/src/components/media-gallery.tsx
import { useRef, useState } from "react";
import { MediaThumb } from "@/components/media-thumb";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
import type { LightboxItem, MediaItem, SearchRow } from "@/lib/types";

export function MediaGallery({
  row,
  onOpen,
  className
}: {
  readonly row: SearchRow;
  readonly onOpen: (item: LightboxItem) => void;
  readonly className?: string;
}) {
  const initial = row.media_items.filter((media) => media && media.media_url);
  const [items, setItems] = useState<readonly MediaItem[]>(initial);
  const expanded = useRef(false);

  const expandAlbum = (): void => {
    if (expanded.current || initial.length > 1) return;
    expanded.current = true;
    api
      .album(row.id)
      .then((album) => {
        if (album.length > initial.length) setItems(album);
      })
      .catch(() => undefined);
  };

  if (!items.length) return null;

  return (
    <div className={cn("flex flex-wrap gap-2 group-data-[align=end]/message:justify-end", className)}>
      {items.map((media, index) => (
        <MediaThumb
          key={media.media_url + String(media.message_id ?? "")}
          media={media}
          index={index}
          onOpen={onOpen}
          onExpand={expandAlbum}
        />
      ))}
    </div>
  );
}
