// packages/message-archive/web/src/lib/components/results-table.svelte
<script lang="ts">
  import { Image as ImageIcon, ScrollText, Search as SearchIcon, ChevronLeft, ChevronRight } from "lucide-svelte";
  import Badge from "$lib/components/ui/badge.svelte";
  import Button from "$lib/components/ui/button.svelte";
  import MediaGallery from "$lib/components/media-gallery.svelte";
  import HighlightedText from "$lib/highlight.svelte";
  import { formatDisplayName, formatMessageDate } from "$lib/format";
  import type { LightboxItem, SearchQuery, SearchRow } from "$lib/types";

  const PAGE_SIZE = 50;

  let {
    query,
    items,
    total,
    page,
    loading,
    error,
    onOpenContext,
    onOpenMedia,
    onPrev,
    onNext
  }: {
    query: SearchQuery | null;
    items: readonly SearchRow[];
    total: number;
    page: number;
    loading: boolean;
    error: string | null;
    onOpenContext: (row: SearchRow) => void;
    onOpenMedia: (item: LightboxItem) => void;
    onPrev: () => void;
    onNext: () => void;
  } = $props();

  const keyword = $derived(query?.keyword ?? "");
  const pageCount = $derived(Math.max(1, Math.ceil(total / PAGE_SIZE)));
  const meta = $derived(
    loading
      ? "查询中..."
      : query
        ? `共 ${total} 条 · 第 ${page} / ${pageCount} 页 · 本页 ${items.length} 条`
        : "暂无结果"
  );
</script>

<div class="min-w-0 rounded-lg border bg-card text-card-foreground shadow-sm">
  <div class="flex flex-col gap-1.5 p-6">
    <h3 class="font-display text-base font-semibold leading-none tracking-tight">查询结果</h3>
    <p class="text-sm text-muted-foreground">{meta}</p>
  </div>
  <div class="p-6 pt-0">
    {#if error}
      <div role="alert" class="relative w-full rounded-lg border border-destructive/50 px-4 py-3 text-sm text-destructive dark:border-destructive [&_svg:not([class*='size-'])]:size-4 [&_svg]:shrink-0 [&_svg]:text-destructive">
        <div class="inline-flex items-center gap-2 font-medium">查询失败</div>
        <div class="text-sm [&_p]:leading-relaxed">{error}</div>
      </div>
    {/if}
    {#if !loading && items.length === 0}
      <div class="flex min-h-64 flex-col items-center justify-center gap-2 text-center">
        <span class="flex size-10 items-center justify-center rounded-full bg-muted">
          <SearchIcon class="size-5 text-muted-foreground" aria-hidden="true" />
        </span>
        <p class="text-sm font-medium">{query ? "没有匹配结果" : "尚未查询"}</p>
        <p class="max-w-sm text-xs text-muted-foreground">
          {query ? "尝试放宽关键词或调整时间范围" : "在左侧填写检索条件后开始查询"}
        </p>
      
      </div>
    {:else}
      <div class="relative w-full overflow-auto"><table class="w-full caption-bottom text-sm">
        <thead class="[&_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/40 data-[state=selected]:bg-muted">
            <th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0">消息内容</th>
            <th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 w-24">上下文</th>
          </tr>
        </thead>
        <tbody class="[&_tr:last-child]:border-0">
          {#if loading && items.length === 0}
            {#each [0, 1, 2, 3, 4] as index (index)}
              <tr class="border-b transition-colors hover:bg-muted/40 data-[state=selected]:bg-muted">
                <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0">
                  <div class="flex flex-col gap-2 py-1">
                    <div class="animate-pulse rounded-md bg-muted h-4 w-2/3"></div>
                    <div class="animate-pulse rounded-md bg-muted h-3 w-full"></div>
                    <div class="animate-pulse rounded-md bg-muted h-3 w-1/2"></div>
                  </div>
                </td>
                <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0">
                  <div class="animate-pulse rounded-md bg-muted h-7 w-16"></div>
                </td>
              </tr>
            {/each}
          {:else}
            {#each items as row (row.id)}
              <tr class="border-b transition-colors hover:bg-muted/40 data-[state=selected]:bg-muted">
                <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 align-top">
                  <div class="flex flex-col gap-2 py-1">
                    <div class="flex flex-wrap items-center gap-1.5">
                      <Badge variant="outline" class="font-mono text-[11px]">{formatMessageDate(row.date)}</Badge>
                      <Badge variant="secondary" class="max-w-full break-words" title={row.chat_title ?? undefined}>
                        {row.chat_title || "未知群组"}
                      </Badge>
                      {#if row.sender_username}
                        <Badge variant="ghost" class="font-mono text-[11px]">@{row.sender_username}</Badge>
                      {:else}
                        <Badge variant="ghost" class="text-[11px]">{formatDisplayName(row)}</Badge>
                      {/if}
                      {#if row.has_media}
                        <Badge variant="secondary">
                          <ImageIcon class="size-3.5" aria-hidden="true" />
                          媒体
                        </Badge>
                      {/if}
                    </div>
                    <p class="whitespace-pre-wrap text-sm leading-relaxed">
                      <HighlightedText text={row.text} keyword={keyword} />
                    </p>
                    <MediaGallery row={row} onOpen={onOpenMedia} />
                  </div>
                </td>
                <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 align-top">
                  <Button variant="ghost" size="sm" onclick={() => onOpenContext(row)}>
                    <ScrollText class="size-4" aria-hidden="true" />
                    上下文
                  </Button>
                </td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table></div>
    {/if}
  </div>
  {#if items.length > 0}
    <div class="flex flex-wrap items-center justify-between gap-3 p-6 pt-0">
      <p class="text-xs text-muted-foreground">第 {page} / {pageCount} 页</p>
      <div class="flex items-center gap-2">
        <Button variant="outline" size="sm" onclick={onPrev} disabled={page <= 1 || loading}>
          <ChevronLeft class="size-4" aria-hidden="true" />
          上一页
        </Button>
        <Button variant="outline" size="sm" onclick={onNext} disabled={page >= pageCount || loading}>
          下一页
          <ChevronRight class="size-4" aria-hidden="true" />
        </Button>
      </div>
    </div>
  {/if}
</div>

// packages/message-archive/web/src/components/results-table.tsx
import { ImageIcon, ScrollTextIcon, SearchIcon } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationNext,
  PaginationPrevious
} from "@/components/ui/pagination";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MediaGallery } from "@/components/media-gallery";
import { formatDisplayName, formatMessageDate } from "@/lib/format";
import { HighlightedText } from "@/lib/highlight";
import type { LightboxItem, SearchQuery, SearchRow } from "@/lib/types";

const PAGE_SIZE = 50;

function MessageCell({
  row,
  keyword,
  onOpenMedia
}: {
  readonly row: SearchRow;
  readonly keyword: string;
  readonly onOpenMedia: (item: LightboxItem) => void;
}) {
  return (
    <div className="flex flex-col gap-2 py-1">
      <div className="flex flex-wrap items-center gap-1.5">
        <Badge variant="outline" className="font-mono text-[11px]">
          {formatMessageDate(row.date)}
        </Badge>
        <Badge variant="secondary" className="max-w-full whitespace-normal break-words" title={row.chat_title ?? undefined}>
          {row.chat_title || "未知群组"}
        </Badge>
        {row.sender_username ? (
          <Badge variant="ghost" className="font-mono text-[11px]">
            @{row.sender_username}
          </Badge>
        ) : (
          <Badge variant="ghost" className="text-[11px]">
            {formatDisplayName(row)}
          </Badge>
        )}
        {row.has_media ? (
          <Badge variant="secondary">
            <ImageIcon />
            媒体
          </Badge>
        ) : null}
      </div>
      <p className="text-sm leading-relaxed whitespace-pre-wrap">
        <HighlightedText text={row.text} keyword={keyword} />
      </p>
      <MediaGallery row={row} onOpen={onOpenMedia} />
    </div>
  );
}

interface ResultsTableProps {
  readonly query: SearchQuery | null;
  readonly items: readonly SearchRow[];
  readonly total: number;
  readonly page: number;
  readonly loading: boolean;
  readonly error: string | null;
  readonly onOpenContext: (row: SearchRow) => void;
  readonly onOpenMedia: (item: LightboxItem) => void;
  readonly onPrev: () => void;
  readonly onNext: () => void;
}

export function ResultsTable({
  query,
  items,
  total,
  page,
  loading,
  error,
  onOpenContext,
  onOpenMedia,
  onPrev,
  onNext
}: ResultsTableProps) {
  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const keyword = query?.keyword ?? "";
  const meta = loading
    ? "查询中..."
    : query
      ? `共 ${total} 条 · 第 ${page} / ${pageCount} 页 · 本页 ${items.length} 条`
      : "暂无结果";

  return (
    <Card className="min-w-0">
      <CardHeader>
        <CardTitle className="font-display text-base">查询结果</CardTitle>
        <CardDescription>{meta}</CardDescription>
      </CardHeader>
      <CardContent>
        {error ? (
          <Alert variant="destructive">
            <AlertTitle>查询失败</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : null}
        {!loading && items.length === 0 ? (
          <Empty className="min-h-64">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <SearchIcon />
              </EmptyMedia>
              <EmptyTitle>{query ? "没有匹配结果" : "尚未查询"}</EmptyTitle>
              <EmptyDescription>
                {query ? "尝试放宽关键词或调整时间范围" : "在左侧填写检索条件后开始查询"}
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>消息内容</TableHead>
                <TableHead className="w-24">上下文</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading && items.length === 0
                ? Array.from({ length: 5 }, (_, index) => (
                    <TableRow key={index}>
                      <TableCell>
                        <div className="flex flex-col gap-2 py-1">
                          <Skeleton className="h-4 w-2/3" />
                          <Skeleton className="h-3 w-full" />
                          <Skeleton className="h-3 w-1/2" />
                        </div>
                      </TableCell>
                      <TableCell>
                        <Skeleton className="h-7 w-16" />
                      </TableCell>
                    </TableRow>
                  ))
                : items.map((row) => (
                    <TableRow key={row.id}>
                      <TableCell className="align-top">
                        <MessageCell row={row} keyword={keyword} onOpenMedia={onOpenMedia} />
                      </TableCell>
                      <TableCell className="align-top">
                        <Button variant="ghost" size="sm" onClick={() => onOpenContext(row)}>
                          <ScrollTextIcon data-icon="inline-start" />
                          上下文
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
      {items.length > 0 ? (
        <CardFooter className="flex-wrap justify-between gap-3">
          <p className="text-xs text-muted-foreground">第 {page} / {pageCount} 页</p>
          <Pagination className="w-auto">
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious
                  text="上一页"
                  href="#"
                  onClick={(event) => {
                    event.preventDefault();
                    if (page > 1) onPrev();
                  }}
                />
              </PaginationItem>
              <PaginationItem>
                <PaginationNext
                  text="下一页"
                  href="#"
                  onClick={(event) => {
                    event.preventDefault();
                    if (page < pageCount) onNext();
                  }}
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </CardFooter>
      ) : null}
    </Card>
  );
}
