// packages/message-archive/web/src/lib/components/search-form.svelte
<script lang="ts">
  import { Search } from "lucide-svelte";
  import Button from "$lib/components/ui/button.svelte";
  import Label from "$lib/components/ui/label.svelte";
  import Select from "$lib/components/ui/select.svelte";
  import Spinner from "$lib/components/ui/spinner.svelte";
  import { toIsoString } from "$lib/format";
  import type { SearchQuery, TimeMode } from "$lib/types";

  let { loading, onSubmit }: { loading: boolean; onSubmit: (query: SearchQuery) => void } = $props();

  let keyword = $state("");
  let excludeKeyword = $state("");
  let chatTitle = $state("");
  let timeMode = $state<TimeMode>("include");
  let dateFrom = $state("");
  let dateTo = $state("");

  const TIME_OPTIONS = [
    { value: "include", label: "包含时间区间" },
    { value: "exclude", label: "不包含时间区间" },
    { value: "off", label: "不按时间筛选" }
  ];

  function switchTimeMode(value: string): void {
    timeMode = value as TimeMode;
  }

  $effect(() => {
    if (timeMode === "off") {
      if (dateFrom !== "") dateFrom = "";
      if (dateTo !== "") dateTo = "";
    }
  });

  function submit(event: SubmitEvent): void {
    event.preventDefault();
    if (loading) return;
    onSubmit({
      keyword: keyword.trim(),
      excludeKeyword: excludeKeyword.trim(),
      chatTitle: chatTitle.trim(),
      dateFrom: timeMode === "off" ? "" : toIsoString(dateFrom),
      dateTo: timeMode === "off" ? "" : toIsoString(dateTo),
      timeMode
    });
  }
</script>

<div class="rounded-lg border bg-card text-card-foreground shadow-sm">
  <div class="flex flex-col gap-1.5 p-6">
    <h3 class="font-display text-base font-semibold leading-none tracking-tight">检索条件</h3>
  </div>
  <div class="p-6 pt-0">
    <form onsubmit={submit} novalidate class="flex flex-col gap-5">
      <div class="flex flex-col gap-4">
        <div class="flex flex-col gap-1.5">
          <Label for="form-keyword">关键词</Label>
          <input class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
            id="form-keyword"
            bind:value={keyword}
            placeholder="多个关键词用空格分隔，例如 clash 节点 香港"
          />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="form-exclude-keyword">不显示关键词</Label>
          <input class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
            id="form-exclude-keyword"
            bind:value={excludeKeyword}
            placeholder="多个关键词用空格分隔，例如 广告 抽奖"
          />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="form-chat-title">群组名称</Label>
          <input class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50" id="form-chat-title" bind:value={chatTitle} placeholder="支持模糊匹配，例如 技术群" />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="form-time-mode">时间筛选</Label>
          <Select id="form-time-mode" bind:value={timeMode} options={TIME_OPTIONS} />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="form-date-from">开始时间</Label>
          <input class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
            id="form-date-from"
            type="datetime-local"
            bind:value={dateFrom}
            disabled={timeMode === "off"}
          />
        </div>
        <div class="flex flex-col gap-1.5">
          <Label for="form-date-to">结束时间</Label>
          <input class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
            id="form-date-to"
            type="datetime-local"
            bind:value={dateTo}
            disabled={timeMode === "off"}
          />
        </div>
      </div>
      <Button type="submit" class={loading ? "cursor-wait" : undefined}>
        {#if loading}
          <Spinner class="size-4" />
        {:else}
          <Search class="size-4" aria-hidden="true" />
        {/if}
        查询
      </Button>
    </form>
  </div>
</div>

// packages/message-archive/web/src/components/search-form.tsx
import { useState, type FormEvent } from "react";
import { SearchIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { toIsoString } from "@/lib/format";
import type { SearchQuery, TimeMode } from "@/lib/types";

interface SearchFormProps {
  readonly loading: boolean;
  readonly onSubmit: (query: SearchQuery) => void;
}

export function SearchForm({ loading, onSubmit }: SearchFormProps) {
  const [keyword, setKeyword] = useState("");
  const [excludeKeyword, setExcludeKeyword] = useState("");
  const [chatTitle, setChatTitle] = useState("");
  const [timeMode, setTimeMode] = useState<TimeMode>("include");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  const switchTimeMode = (value: string): void => {
    const next = value as TimeMode;
    setTimeMode(next);
    if (next === "off") {
      setDateFrom("");
      setDateTo("");
    }
  };

  const submit = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    if (loading) return;
    onSubmit({
      keyword: keyword.trim(),
      excludeKeyword: excludeKeyword.trim(),
      chatTitle: chatTitle.trim(),
      dateFrom: timeMode === "off" ? "" : toIsoString(dateFrom),
      dateTo: timeMode === "off" ? "" : toIsoString(dateTo),
      timeMode
    });
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-display text-base">检索条件</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={submit} noValidate className="flex flex-col gap-5">
          <FieldGroup>
            <Field>
              <FieldLabel htmlFor="form-keyword">关键词</FieldLabel>
              <Input
                id="form-keyword"
                placeholder="多个关键词用空格分隔，例如 clash 节点 香港"
                value={keyword}
                onChange={(event) => setKeyword(event.target.value)}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="form-exclude-keyword">不显示关键词</FieldLabel>
              <Input
                id="form-exclude-keyword"
                placeholder="多个关键词用空格分隔，例如 广告 抽奖"
                value={excludeKeyword}
                onChange={(event) => setExcludeKeyword(event.target.value)}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="form-chat-title">群组名称</FieldLabel>
              <Input
                id="form-chat-title"
                placeholder="支持模糊匹配，例如 技术群"
                value={chatTitle}
                onChange={(event) => setChatTitle(event.target.value)}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="form-time-mode">时间筛选</FieldLabel>
              <Select value={timeMode} onValueChange={switchTimeMode}>
                <SelectTrigger id="form-time-mode">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="include">包含时间区间</SelectItem>
                    <SelectItem value="exclude">不包含时间区间</SelectItem>
                    <SelectItem value="off">不按时间筛选</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>
            <Field>
              <FieldLabel htmlFor="form-date-from">开始时间</FieldLabel>
              <Input
                id="form-date-from"
                type="datetime-local"
                value={dateFrom}
                disabled={timeMode === "off"}
                onChange={(event) => setDateFrom(event.target.value)}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="form-date-to">结束时间</FieldLabel>
              <Input
                id="form-date-to"
                type="datetime-local"
                value={dateTo}
                disabled={timeMode === "off"}
                onChange={(event) => setDateTo(event.target.value)}
              />
            </Field>
          </FieldGroup>
          <Button type="submit" aria-busy={loading} className={loading ? "cursor-wait" : undefined}>
            {loading ? <Spinner data-icon="inline-start" /> : <SearchIcon data-icon="inline-start" />}
            查询
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
