// packages/message-archive/web/src/lib/highlight.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  export interface HighlightToken {
    readonly kind: "text" | "mark" | "link";
    readonly text: string;
    readonly url?: string;
  }

  function escapeRegExp(text: string): string {
    return String(text).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  function highlightTerms(keyword: string): string[] {
    return Array.from(
      new Set(
        keyword
          .split(/\s+/)
          .map((term) => term.trim())
          .filter(Boolean)
      )
    ).sort((left, right) => right.length - left.length);
  }

  const LINK_PATTERN = /\[([^\][]*)\]\(([^)]+)\)|((?:https?:\/\/|www\.|t\.me\/)[^\s<>"'，。；：！？、（）《》〈〉【】]+)/g;

  function normalizeLinkUrl(value: string): string | undefined {
    const url = value.trim().replace(/[)\]》，。；：！？、…]+$/g, "");
    if (/^(?:https?|tg):\/\//i.test(url)) return url;
    if (/^t\.me\//i.test(url) || /^www\./i.test(url)) return `https://${url}`;
    return undefined;
  }

  function matchesTerm(part: string, terms: readonly string[]): boolean {
    return terms.some(
      (term) => term.localeCompare(part, undefined, { sensitivity: "accent" }) === 0 || term.toLowerCase() === part.toLowerCase()
    );
  }

  function tokenize(text: string, terms: readonly string[]): HighlightToken[] {
    const tokens: HighlightToken[] = [];
    const pushHighlighted = (part: string): void => {
      if (!part) return;
      if (!terms.length) {
        tokens.push({ kind: "text", text: part });
        return;
      }
      const pattern = new RegExp(`(${terms.map(escapeRegExp).join("|")})`, "gi");
      for (const piece of part.split(pattern)) {
        if (!piece) continue;
        tokens.push(matchesTerm(piece, terms) ? { kind: "mark", text: piece } : { kind: "text", text: piece });
      }
    };
    let cursor = 0;
    for (const match of text.matchAll(LINK_PATTERN)) {
      const index = match.index ?? 0;
      if (index > cursor) pushHighlighted(text.slice(cursor, index));
      const [, label, markdownUrl, bareUrl] = match;
      const url = normalizeLinkUrl(markdownUrl ?? bareUrl ?? "");
      if (url === undefined) {
        pushHighlighted(match[0]);
      } else {
        tokens.push({ kind: "link", text: label ?? match[0], url });
      }
      cursor = index + match[0].length;
    }
    if (cursor < text.length) pushHighlighted(text.slice(cursor));
    return tokens;
  }

  let { text, keyword, class: className = "" }: { text: string | null | undefined; keyword: string; class?: string } = $props();

  const tokens = $derived(tokenize(text ?? "", highlightTerms(keyword)));
</script>

<span class={cn("break-words", className)}>
  {#each tokens as token, index (index)}
    {#if token.kind === "mark"}
      <mark class="rounded-[3px] bg-foreground/12 px-0.5 text-foreground">{token.text}</mark>
    {:else if token.kind === "link"}
      <a
        href={token.url}
        target="_blank"
        rel="noreferrer"
        class="break-all text-foreground underline decoration-foreground/40 underline-offset-2 hover:decoration-foreground"
      >
        {token.text}
      </a>
    {:else}
      {token.text}
    {/if}
  {/each}
</span>

// packages/message-archive/web/src/lib/highlight.tsx
import { useMemo, type ReactNode } from "react";
import { cn } from "@/lib/utils";

export function highlightTerms(keyword: string): string[] {
  return Array.from(
    new Set(
      keyword
        .split(/\s+/)
        .map((term) => term.trim())
        .filter(Boolean)
    )
  ).sort((left, right) => right.length - left.length);
}

function escapeRegExp(text: string): string {
  return String(text).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function matchesTerm(part: string, terms: readonly string[]): boolean {
  return terms.some(
    (term) => term.localeCompare(part, undefined, { sensitivity: "accent" }) === 0 || term.toLowerCase() === part.toLowerCase()
  );
}

const LINK_PATTERN = /\[([^\][]*)\]\(([^)]+)\)|((?:https?:\/\/|www\.|t\.me\/)[^\s<>"'，。；：！？、（）《》〈〉【】]+)/g;

function normalizeLinkUrl(value: string): string | undefined {
  const url = value.trim().replace(/[)\]》，。；：！？、…]+$/g, "");
  if (/^(?:https?|tg):\/\//i.test(url)) return url;
  if (/^t\.me\//i.test(url) || /^www\./i.test(url)) return `https://${url}`;
  return undefined;
}

function pushHighlighted(nodes: ReactNode[], text: string, terms: readonly string[], nextKey: () => number): void {
  if (!text) return;
  if (!terms.length) {
    nodes.push(text);
    return;
  }
  const pattern = new RegExp(`(${terms.map(escapeRegExp).join("|")})`, "gi");
  for (const part of text.split(pattern)) {
    if (!part) continue;
    if (!matchesTerm(part, terms)) {
      nodes.push(part);
      continue;
    }
    nodes.push(
      <mark key={nextKey()} className={cn("rounded-[3px] bg-primary/15 px-0.5 text-foreground")}>
        {part}
      </mark>
    );
  }
}

function tokenize(text: string, terms: readonly string[]): ReactNode[] {
  const nodes: ReactNode[] = [];
  let key = 0;
  const nextKey = (): number => key++;
  let cursor = 0;
  for (const match of text.matchAll(LINK_PATTERN)) {
    const index = match.index ?? 0;
    if (index > cursor) pushHighlighted(nodes, text.slice(cursor, index), terms, nextKey);
    const [, label, markdownUrl, bareUrl] = match;
    const url = normalizeLinkUrl(markdownUrl ?? bareUrl ?? "");
    if (url === undefined) {
      pushHighlighted(nodes, match[0], terms, nextKey);
    } else {
      nodes.push(
        <a
          key={nextKey()}
          href={url}
          target="_blank"
          rel="noreferrer"
          className="break-all text-primary underline decoration-primary/40 underline-offset-2 hover:decoration-primary"
        >
          {label ?? match[0]}
        </a>
      );
    }
    cursor = index + match[0].length;
  }
  if (cursor < text.length) pushHighlighted(nodes, text.slice(cursor), terms, nextKey);
  return nodes;
}

export function HighlightedText({
  text,
  keyword,
  className
}: {
  readonly text: string | null | undefined;
  readonly keyword: string;
  readonly className?: string;
}) {
  const terms = useMemo(() => highlightTerms(keyword), [keyword]);
  const nodes = useMemo(() => tokenize(text ?? "", terms), [text, terms]);
  return <span className={cn("wrap-break-word", className)}>{nodes}</span>;
}
